### ISSUE TITLE
Design Library.

### ISSUE THREAD

**Issue by deepakbarmola** [ColoredCow/goonj-crm#14]
We need to establish a Design system for the UI of components used in the Goonj CRM. This ticket will address the basic foundation, including the following items. 
1. Font and colors used as per Goonj's branding
2. Builder Components which we can use for forms and other UI elements.

**Comment by HKKohli** [comment]
**Update**

Initial fonts & colors have been identified based on the Goonj website ([link](https://www.figma.com/design/1zsZGbJHqcGvvToWDthSRb/Goonj-CRM?node-id=1-4))

![image](https://github.com/ColoredCow/goonj-crm/assets/69384907/e2dc4935-94e4-4073-a56d-6abf0011ee95)
