### ISSUE TITLE
Evaluating automation tools(Playwright, cypress) for the project based on below parameter

### ISSUE THREAD

**Issue by deepakbarmola** [ColoredCow/goonj-crm#34]
- [x] Performance
- [x] Scalability
- [x] Compatibility

**Comment by deepankar-sajwan** [comment]
Based on the research we have complied our analysis in the below sheet 

https://docs.google.com/spreadsheets/d/1d2SzmWJSTOoeIqNPnXFqbB9QbsiNUbx5P4yn_DDescg/edit#gid=0

As per our analysis playwright is better suited for our project. Apart from the evaluation parameters used for analysis there is below link related
