### ISSUE TITLE
Prototype: Basic Registration Workflow

### ISSUE THREAD

**Issue by deep4k-tripathi** [ColoredCow/goonj-crm#6]
## Functional Requirements for the Registration workflow

In this issue, we are tracking all the requirements to execute the prototype for the registration workflow within the CRM. The prototype will include the registration workflow for both individual and institutional stakeholders.

### Registration - Individuals

The registration process is essential for entering contact information into the contact database. This helps us gather information about the stakeholders who are linked to Goonj and details about their engagement.

**User Journey for Individual Registration**
The individual registration process allows stakeholders to connect with Goonj through various entry points: 
1. Stakeholders can register through a link on the Goonj website, via a WhatsApp share/chat bot, using a QR code during event registration, at drop-off centers, collection camps, or during events. Additionally, a Goonj team member can manually register the stakeholder.
2. When initiating the registration process, the system will verify if the user is a first-time registrant or if they are already registered. This is determined based on configurable key parameters such as mobile number or email.
3. The registration form will capture and store the origin of the registration (e.g., specific QR code or link) to understand how the user landed on the registration page.
4. The form will feature multiple configurable sections, including a basic registration section and a detailed information section. The sections displayed to the user will vary based on the origin of the registration.
5. The basic form will collect essential information such as name, contact information, city, and state.
6. If a detailed form is required (e.g., for volunteers or when filled out by a Goonj team member), additional fields will be displayed, including age group, gender, address, status, and tags. These fields will also be configurable.
7. Upon submission, automatic acknowledgment emails or messages will be sent to the user and optionally to team members. The content of these emails/messages will depend on the user's selections and will be based on predefined templates.
8. Help texts will be provided in the forms to assist users in completing the registration.
9. Once the form is filled and submitted, an entry will be made for the registered individual in the contact database

[Workflow Diagram](https://miro.com/app/board/uXjVKIoC4h0=/?moveToWidget=3458764589628120090&cot=14): 
![image](https://github.com/ColoredCow/civicrm/assets/83333080/57ee6203-6f63-4b9d-917c-bcd71f9933b7)

-----

### Registration - Institutions

In this context, institutions can include educational institutions, corporates, FMCG companies, bulk manufacturers, dry cleaners, youth groups, associations, philanthropic foundations, hotels, housing societies, and clubs (e.g., Rotaries). The registration process for institutions is designed to cater to groups rather than individuals.

**User Journey for Institutional Registration**
The institution registration process facilitates the connection of groups with Goonj through various methods:
1. Institutions can register directly using QR codes or links, or a Goonj employee can manually register the institution.
2. The institution registration form will have configurable sections.
3. The form will collect comprehensive information including the type of institution, institution details (name, branch, department hierarchy if applicable), address, and contact information. The contact information will be linked in a one-to-many relationship, capturing details such as name, profile (e.g., CSR Head, Teacher, PTA Secretary based on the institution type), status (active/inactive), and contact details. Individuals associated with the institution will automatically be registered as individuals if they are not already in the database.
4. Additional information collected will include the size of the institution, the Goonj team member attached (with a history of changes if applicable), and the initiation source (Goonj or the institution).
5. Upon form submission, an entry will be made for the registered institution in the contact database.
6. The system will maintain a history of the contact information associated with the institution, ensuring that the point of contact is part of the individual registration as well.
7. A field will indicate whether the institution is onboarded. If the registration is created by a Goonj member and the onboarded field is not selected, the status will be “Initial.” If the onboarded field is selected, the status will be “Onboarded.” If the registration is done directly by the institution, the status will be “Initial.”
8. Checkboxes will be available for the team to confirm whether the institution has political or religious affiliations. Team members will update the status field to “Onboarded” or “Blocked” after due diligence, including reasons for a “Blocked” status.
9. If the status is set to “Onboarded,” a registration confirmation email will be sent to both the associated Goonj member and the institution. If not, the email will be sent only to the Goonj team member.

[Workflow Diagram](https://miro.com/app/board/uXjVKIoC4h0=/?moveToWidget=3458764589628120090&cot=14): 
![image](https://github.com/ColoredCow/civicrm/assets/83333080/dd4cb0fa-eccc-4214-a278-e5b267c337e5)

**Comment by deepankar-sajwan** [comment]
Test case scenarios for individual  user registration in desktop and mobile view 

- Verify user can register through below methods for registration
    - Through link on the Goonj website
    - WhatsApp share/chat bot
    - QR code during event registration
    - Drop-off centers
    - Collection camps
    - In events
    - Manual registration through goonj team member

- Verify below cases in basic form
   - Validation of input fields for allowable input based on character or digit type and their length
   - Submission of form without providing input for optional fields
   - Non Submission of form without providing input for mandatory fields
   - Help text in the form 
   - Disabling of multiple request on clicking submit button
 
   
- Verify below cases after form submission
    - Identification of source of registration based on type of form basic or detail
    - Check user is registering for first time or already exist based on mobile number or email id 
    - Check details of submitted form in the database, if new user detail should be added for existing 
       details should not be updated 
    - Mandatory email trigger to individual, and also for team member if option enabled for mail trigger
   
- Verify below UI aspects as per design the form

**Comment by deepankar-sajwan** [comment]
Test case scenarios for institutional  registration in desktop and mobile view

- Verify user can register through below methods for registration
    - QR code
    - Through Link
    - Manual registration by goonj team member

- Verify below cases in detail form
    - Validation of input fields for allowable input based on character or digit type and their length
    - Error message associated with input fields validation
    - Submission of form without providing input for optional fields
    - Non Submission of form without providing input for mandatory fields
    - Disabling of multiple request on clicking submit button
    - Verify below cases after form submission

Verify below cases after form submission
- Identification of source of registration based on type of form basic or detail
- Check institution is already registered or new registration
- Check details of submitted form in the database, if new registration for institution then details should be added in 
   database.
- Update the database if goonj team member detials are available
- In case Goonj team member select 'onboarded' status, then mail should be triggered to both Goonj member and 
   institute
- In case Goonj team member does not select 'onboarded' status, then mail should be triggered to only Goonj member
  only an status set as `initial`
 - If status for institute registration set as initial and team reviewer set status as Onboarded then email will be triggered
   to both goonj member and institute
- If status for institute registration set as initial and team reviewer set status as Blocked  then email will be triggered
   to both goonj member only

**Comment by deepankar-sajwan** [comment]
Scenarios related to user access based on the user role are listed below

- Individual registration
   - View the form 
   - Submission of the form
   - Receiving email's or message

- Goonj Team Member (Individual Stakeholder)
    - Register individual member
    - Check if registered user is existing or new on admin or database
    - Verify user registration source QR code or link 
    - Able to configure different sections of the basic form on admin side
    - Collect and store all registration details for basic form
    - Receive and view configurable emails/messages
    - Addition of help text in the form through admin site
    - Make entries for registered individuals in database or admin site
    
- Institute registration
    - View the form 
   - Submission of the form
   - Receiving email's or message
   
- Goonj Team Member (Institute registration)
   - Register institute 
   - Configure different fields  of the details form
   - Capture  and store institution details in the database
   - Associating individual with related institute 
   - Tracking updated changes and history for updated info
   - Assigning onboarded status
   - Validating religious and political affiliations
   - Validating the status after review as “Onboarded” or “Blocked” 
  - Receive and send registration emails
